# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 614)
        MainWindow.setStyleSheet("")
        self.styles = QtWidgets.QWidget(MainWindow)
        self.styles.setStyleSheet("/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"SET APP STYLESHEET - FULL STYLES HERE\n"
"DARK THEME - DRACULA COLOR BASED\n"
"\n"
"///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"QWidget{\n"
"    color: rgb(221, 221, 221);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(33, 37, 43, 180);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Bg App */\n"
"#bgApp {    \n"
"    background-color: rgb(40, 44, 52);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"#topLogo {\n"
"    background-color: rgb(33, 37, 43);\n"
"    background-image: url(:/images/images/images/PyDracula.png);\n"
"    background-position: centered;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"#titleLeftApp { font: 63 12pt \"Segoe UI Semibold\"; }\n"
"#titleLeftDescription { font: 8pt \"Segoe UI\"; color: rgb(189, 147, 249); }\n"
"\n"
"/* MENUS */\n"
"QPushButton {    \n"
"    border: none;\n"
"    background-color: rgba(91, 100, 118);\n"
"    text-align: center;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#bottomMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: center;\n"
"}\n"
"#bottomMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#bottomMenu .QPushButton:pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color: rgb(37, 41, 48);\n"
"    text-align: left;\n"
"    color: rgb(113, 126, 149);\n"
"}\n"
"#toggleButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#toggleButton:pressed {\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Extra Tab */\n"
"#extraLeftBox {    \n"
"    background-color: rgb(44, 49, 58);\n"
"}\n"
"#extraTopBg{    \n"
"    background-color: rgb(189, 147, 249)\n"
"}\n"
"\n"
"/* Icon */\n"
"#extraIcon {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-image: url(:/icons/images/icons/icon_settings.png);\n"
"}\n"
"\n"
"/* Label */\n"
"#extraLabel { color: rgb(255, 255, 255); }\n"
"\n"
"/* Btn Close */\n"
"#extraCloseColumnBtn { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#extraCloseColumnBtn:hover { background-color: rgb(196, 161, 249); border-style: solid; border-radius: 4px; }\n"
"#extraCloseColumnBtn:pressed { background-color: rgb(180, 141, 238); border-style: solid; border-radius: 4px; }\n"
"\n"
"/* Extra Content */\n"
"#extraContent{\n"
"    border-top: 3px solid rgb(40, 44, 52);\n"
"}\n"
"\n"
"/* Extra Top Menus */\n"
"#extraTopMenu .QPushButton {\n"
"background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"}\n"
"#extraTopMenu .QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#extraTopMenu .QPushButton:pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Content App */\n"
"#contentTopBg{    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"#contentBottom{\n"
"    border-top: 3px solid rgb(44, 49, 58);\n"
"}\n"
"\n"
"\n"
"\n"
"/* Theme Settings */\n"
"#extraRightBox { background-color: rgb(44, 49, 58); }\n"
"#themeSettingsTopDetail { background-color: rgb(189, 147, 249); }\n"
"\n"
"\n"
"QLabel { \n"
"font-size: 18px; \n"
"color: rgb(0, 0, 0);\n"
"padding-right: 10px; \n"
"padding-bottom: 2px;\n"
" }\n"
"\n"
"/* CONTENT SETTINGS */\n"
"/* MENUS */\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {    \n"
"    background-color: transparent;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 58);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(33, 37, 43);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(33, 37, 43);\n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"    background-color: rgba(91, 100, 118);\n"
"    \n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(33, 37, 43);\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(189, 147, 249);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(189, 147, 249);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 121, 198);    \n"
"    background-color: rgb(33, 37, 43);\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"QCommandLinkButton {    \n"
"    color: rgb(255, 121, 198);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 170, 255);\n"
"}\n"
"QCommandLinkButton:hover {    \n"
"    color: rgb(255, 170, 255);\n"
"    background-color: rgb(44, 49, 60);\n"
"}\n"
"QCommandLinkButton:pressed {    \n"
"    color: rgb(189, 147, 249);\n"
"    background-color: rgb(52, 58, 71);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"")
        self.styles.setObjectName("styles")
        self.widget = QtWidgets.QWidget(self.styles)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1091, 611))
        self.widget.setObjectName("widget")
        self.leftMenuFrame = QtWidgets.QFrame(self.widget)
        self.leftMenuFrame.setGeometry(QtCore.QRect(0, 0, 91, 601))
        self.leftMenuFrame.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"QPushButton {\n"
"    border-radius:0px;\n"
"}")
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalMenuLayout = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalMenuLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalMenuLayout.setSpacing(0)
        self.verticalMenuLayout.setObjectName("verticalMenuLayout")
        self.topMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.topMenu.setStyleSheet("border-radius:0px;")
        self.topMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenu.setObjectName("topMenu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.topMenu)
        self.verticalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_girisekrani = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_girisekrani.sizePolicy().hasHeightForWidth())
        self.btn_girisekrani.setSizePolicy(sizePolicy)
        self.btn_girisekrani.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_girisekrani.setFont(font)
        self.btn_girisekrani.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_girisekrani.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_girisekrani.setStyleSheet("")
        self.btn_girisekrani.setObjectName("btn_girisekrani")
        self.verticalLayout_8.addWidget(self.btn_girisekrani)
        self.btn_calisanlar = QtWidgets.QPushButton(self.topMenu)
        self.btn_calisanlar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_calisanlar.sizePolicy().hasHeightForWidth())
        self.btn_calisanlar.setSizePolicy(sizePolicy)
        self.btn_calisanlar.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_calisanlar.setFont(font)
        self.btn_calisanlar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_calisanlar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_calisanlar.setStyleSheet("")
        self.btn_calisanlar.setObjectName("btn_calisanlar")
        self.verticalLayout_8.addWidget(self.btn_calisanlar)
        self.btn_ziyaretci = QtWidgets.QPushButton(self.topMenu)
        self.btn_ziyaretci.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ziyaretci.sizePolicy().hasHeightForWidth())
        self.btn_ziyaretci.setSizePolicy(sizePolicy)
        self.btn_ziyaretci.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_ziyaretci.setFont(font)
        self.btn_ziyaretci.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ziyaretci.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ziyaretci.setStyleSheet("")
        self.btn_ziyaretci.setObjectName("btn_ziyaretci")
        self.verticalLayout_8.addWidget(self.btn_ziyaretci)
        self.btn_raporlar = QtWidgets.QPushButton(self.topMenu)
        self.btn_raporlar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_raporlar.sizePolicy().hasHeightForWidth())
        self.btn_raporlar.setSizePolicy(sizePolicy)
        self.btn_raporlar.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_raporlar.setFont(font)
        self.btn_raporlar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_raporlar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_raporlar.setStyleSheet("")
        self.btn_raporlar.setObjectName("btn_raporlar")
        self.verticalLayout_8.addWidget(self.btn_raporlar)
        self.btn_exit = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exit.sizePolicy().hasHeightForWidth())
        self.btn_exit.setSizePolicy(sizePolicy)
        self.btn_exit.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_exit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_exit.setStyleSheet("")
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_8.addWidget(self.btn_exit)
        self.verticalMenuLayout.addWidget(self.topMenu, 0, QtCore.Qt.AlignTop)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(90, 0, 981, 601))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.giris_sayfasi = QtWidgets.QWidget()
        self.giris_sayfasi.setObjectName("giris_sayfasi")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.giris_sayfasi)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(300, 180, 401, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_kullaniciadi = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_kullaniciadi.setObjectName("lbl_kullaniciadi")
        self.horizontalLayout_6.addWidget(self.lbl_kullaniciadi)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.txt_kullaniciadi = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_kullaniciadi.setMinimumSize(QtCore.QSize(0, 35))
        self.txt_kullaniciadi.setObjectName("txt_kullaniciadi")
        self.horizontalLayout_6.addWidget(self.txt_kullaniciadi)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_sifre = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_sifre.setObjectName("lbl_sifre")
        self.horizontalLayout_3.addWidget(self.lbl_sifre)
        spacerItem1 = QtWidgets.QSpacerItem(70, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.txt_sifre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_sifre.setMinimumSize(QtCore.QSize(0, 35))
        self.txt_sifre.setObjectName("txt_sifre")
        self.horizontalLayout_3.addWidget(self.txt_sifre)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.btn_giris = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_giris.sizePolicy().hasHeightForWidth())
        self.btn_giris.setSizePolicy(sizePolicy)
        self.btn_giris.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_giris.setObjectName("btn_giris")
        self.verticalLayout.addWidget(self.btn_giris)
        self.stackedWidget.addWidget(self.giris_sayfasi)
        self.calisanlar_sayfasi = QtWidgets.QWidget()
        self.calisanlar_sayfasi.setObjectName("calisanlar_sayfasi")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.calisanlar_sayfasi)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(200, 100, 621, 261))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        spacerItem2 = QtWidgets.QSpacerItem(60, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.txt_kullaniciadi_calisan = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.txt_kullaniciadi_calisan.setMinimumSize(QtCore.QSize(0, 35))
        self.txt_kullaniciadi_calisan.setObjectName("txt_kullaniciadi_calisan")
        self.horizontalLayout_10.addWidget(self.txt_kullaniciadi_calisan)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        spacerItem3 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.txt_atanacak = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.txt_atanacak.setMinimumSize(QtCore.QSize(0, 35))
        self.txt_atanacak.setObjectName("txt_atanacak")
        self.horizontalLayout_13.addWidget(self.txt_atanacak)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_9.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_guncelle = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.btn_guncelle.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_guncelle.setObjectName("btn_guncelle")
        self.horizontalLayout_9.addWidget(self.btn_guncelle)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.calisanlar_sayfasi)
        self.ziyaretci_sayfasi = QtWidgets.QWidget()
        self.ziyaretci_sayfasi.setObjectName("ziyaretci_sayfasi")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.ziyaretci_sayfasi)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(490, 40, 461, 341))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_19.addWidget(self.label_25)
        spacerItem4 = QtWidgets.QSpacerItem(115, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.txt_tc = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.txt_tc.setMinimumSize(QtCore.QSize(0, 35))
        self.txt_tc.setObjectName("txt_tc")
        self.horizontalLayout_19.addWidget(self.txt_tc)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_15.addWidget(self.label_21)
        spacerItem5 = QtWidgets.QSpacerItem(110, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.txt_adi = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.txt_adi.setMinimumSize(QtCore.QSize(0, 35))
        self.txt_adi.setObjectName("txt_adi")
        self.horizontalLayout_15.addWidget(self.txt_adi)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_16.addWidget(self.label_22)
        spacerItem6 = QtWidgets.QSpacerItem(85, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.txt_soyadi = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.txt_soyadi.setMinimumSize(QtCore.QSize(0, 35))
        self.txt_soyadi.setObjectName("txt_soyadi")
        self.horizontalLayout_16.addWidget(self.txt_soyadi)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_17.addWidget(self.label_23)
        spacerItem7 = QtWidgets.QSpacerItem(90, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.txt_adres = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.txt_adres.setMinimumSize(QtCore.QSize(0, 35))
        self.txt_adres.setObjectName("txt_adres")
        self.horizontalLayout_17.addWidget(self.txt_adres)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_18.addWidget(self.label_24)
        spacerItem8 = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.btn_resimcek = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_resimcek.setMinimumSize(QtCore.QSize(180, 35))
        self.btn_resimcek.setObjectName("btn_resimcek")
        self.horizontalLayout_18.addWidget(self.btn_resimcek)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_20.addWidget(self.label_26)
        spacerItem9 = QtWidgets.QSpacerItem(45, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.cmb_adres = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.cmb_adres.setMinimumSize(QtCore.QSize(185, 0))
        self.cmb_adres.setObjectName("cmb_adres")
        self.cmb_adres.addItem("")
        self.cmb_adres.addItem("")
        self.cmb_adres.addItem("")
        self.horizontalLayout_20.addWidget(self.cmb_adres)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.ziyareci_kamera = QtWidgets.QLabel(self.ziyaretci_sayfasi)
        self.ziyareci_kamera.setGeometry(QtCore.QRect(10, 20, 461, 270))
        self.ziyareci_kamera.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.ziyareci_kamera.setAlignment(QtCore.Qt.AlignCenter)
        self.ziyareci_kamera.setObjectName("ziyareci_kamera")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.ziyaretci_sayfasi)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(540, 390, 349, 49))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_22.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(15)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.btn_gonder = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_gonder.sizePolicy().hasHeightForWidth())
        self.btn_gonder.setSizePolicy(sizePolicy)
        self.btn_gonder.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_gonder.setFont(font)
        self.btn_gonder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gonder.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_gonder.setStyleSheet("")
        self.btn_gonder.setObjectName("btn_gonder")
        self.horizontalLayout_22.addWidget(self.btn_gonder)
        self.stackedWidget.addWidget(self.ziyaretci_sayfasi)
        self.izleme_sayfasi = QtWidgets.QWidget()
        self.izleme_sayfasi.setObjectName("izleme_sayfasi")
        self.lbl_kameraE = QtWidgets.QLabel(self.izleme_sayfasi)
        self.lbl_kameraE.setGeometry(QtCore.QRect(10, 290, 241, 241))
        self.lbl_kameraE.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_kameraE.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_kameraE.setObjectName("lbl_kameraE")
        self.lbl_kameraF = QtWidgets.QLabel(self.izleme_sayfasi)
        self.lbl_kameraF.setGeometry(QtCore.QRect(260, 290, 241, 241))
        self.lbl_kameraF.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_kameraF.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_kameraF.setObjectName("lbl_kameraF")
        self.lbl_kameraC = QtWidgets.QLabel(self.izleme_sayfasi)
        self.lbl_kameraC.setGeometry(QtCore.QRect(510, 20, 241, 241))
        self.lbl_kameraC.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_kameraC.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_kameraC.setObjectName("lbl_kameraC")
        self.lbl_kameraB = QtWidgets.QLabel(self.izleme_sayfasi)
        self.lbl_kameraB.setGeometry(QtCore.QRect(260, 20, 241, 241))
        self.lbl_kameraB.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_kameraB.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_kameraB.setObjectName("lbl_kameraB")
        self.lbl_kameraG = QtWidgets.QLabel(self.izleme_sayfasi)
        self.lbl_kameraG.setGeometry(QtCore.QRect(510, 290, 241, 241))
        self.lbl_kameraG.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_kameraG.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_kameraG.setObjectName("lbl_kameraG")
        self.lbl_kameraH = QtWidgets.QLabel(self.izleme_sayfasi)
        self.lbl_kameraH.setGeometry(QtCore.QRect(760, 290, 241, 241))
        self.lbl_kameraH.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_kameraH.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_kameraH.setObjectName("lbl_kameraH")
        self.lbl_kameraD = QtWidgets.QLabel(self.izleme_sayfasi)
        self.lbl_kameraD.setGeometry(QtCore.QRect(760, 20, 241, 241))
        self.lbl_kameraD.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_kameraD.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_kameraD.setObjectName("lbl_kameraD")
        self.label_3 = QtWidgets.QLabel(self.izleme_sayfasi)
        self.label_3.setGeometry(QtCore.QRect(580, 260, 111, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.izleme_sayfasi)
        self.label_4.setGeometry(QtCore.QRect(830, 260, 111, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.izleme_sayfasi)
        self.label_5.setGeometry(QtCore.QRect(80, 530, 111, 20))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.izleme_sayfasi)
        self.label_7.setGeometry(QtCore.QRect(330, 530, 111, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.izleme_sayfasi)
        self.label_8.setGeometry(QtCore.QRect(590, 530, 111, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.izleme_sayfasi)
        self.label_9.setGeometry(QtCore.QRect(840, 530, 111, 20))
        self.label_9.setObjectName("label_9")
        self.lbl_kameraA = QtWidgets.QLabel(self.izleme_sayfasi)
        self.lbl_kameraA.setGeometry(QtCore.QRect(10, 20, 241, 241))
        self.lbl_kameraA.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_kameraA.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_kameraA.setObjectName("lbl_kameraA")
        self.label_11 = QtWidgets.QLabel(self.izleme_sayfasi)
        self.label_11.setGeometry(QtCore.QRect(80, 260, 111, 20))
        self.label_11.setObjectName("label_11")
        self.label_27 = QtWidgets.QLabel(self.izleme_sayfasi)
        self.label_27.setGeometry(QtCore.QRect(330, 260, 111, 20))
        self.label_27.setObjectName("label_27")
        self.label = QtWidgets.QLabel(self.izleme_sayfasi)
        self.label.setGeometry(QtCore.QRect(300, 560, 181, 31))
        self.label.setStyleSheet("\n"
"font: 14pt \"Times New Roman\";\n"
"background-color: rgb(0, 255, 0);\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.izleme_sayfasi)
        self.label_2.setGeometry(QtCore.QRect(560, 560, 211, 31))
        self.label_2.setStyleSheet("\n"
"font: 14pt \"Times New Roman\";\n"
"background-color: rgb(255, 0, 4);\n"
"")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.izleme_sayfasi)
        self.raporlar_sayfasi = QtWidgets.QWidget()
        self.raporlar_sayfasi.setObjectName("raporlar_sayfasi")
        self.txt_rapor = QtWidgets.QTextEdit(self.raporlar_sayfasi)
        self.txt_rapor.setGeometry(QtCore.QRect(70, 30, 851, 551))
        self.txt_rapor.setObjectName("txt_rapor")
        self.stackedWidget.addWidget(self.raporlar_sayfasi)
        MainWindow.setCentralWidget(self.styles)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "takip programı"))
        self.btn_girisekrani.setText(_translate("MainWindow", "giris"))
        self.btn_calisanlar.setText(_translate("MainWindow", "Çalışanlar"))
        self.btn_ziyaretci.setText(_translate("MainWindow", "Ziyaretçi"))
        self.btn_raporlar.setText(_translate("MainWindow", "Raporlar"))
        self.btn_exit.setText(_translate("MainWindow", "çıkış"))
        self.lbl_kullaniciadi.setText(_translate("MainWindow", "Kullanıcı Adı"))
        self.lbl_sifre.setText(_translate("MainWindow", "Şifre"))
        self.btn_giris.setText(_translate("MainWindow", "Giriş"))
        self.label_17.setText(_translate("MainWindow", "Kullanıcı Adı"))
        self.label_20.setText(_translate("MainWindow", "Atanacak Kameralar"))
        self.btn_guncelle.setText(_translate("MainWindow", "Güncelle"))
        self.label_25.setText(_translate("MainWindow", "TC"))
        self.label_21.setText(_translate("MainWindow", "Ad"))
        self.label_22.setText(_translate("MainWindow", "Soyad"))
        self.label_23.setText(_translate("MainWindow", "Adres"))
        self.label_24.setText(_translate("MainWindow", "Resim"))
        self.btn_resimcek.setText(_translate("MainWindow", "resim çek"))
        self.label_26.setText(_translate("MainWindow", "Ziyaret E. Kişi"))
        self.cmb_adres.setItemText(0, _translate("MainWindow", "ahmet"))
        self.cmb_adres.setItemText(1, _translate("MainWindow", "mehmet"))
        self.cmb_adres.setItemText(2, _translate("MainWindow", "hasan"))
        self.ziyareci_kamera.setText(_translate("MainWindow", "Kamera"))
        self.btn_gonder.setText(_translate("MainWindow", "gönder"))
        self.lbl_kameraE.setText(_translate("MainWindow", "Kamera"))
        self.lbl_kameraF.setText(_translate("MainWindow", "Kamera"))
        self.lbl_kameraC.setText(_translate("MainWindow", "Kamera"))
        self.lbl_kameraB.setText(_translate("MainWindow", "Kamera"))
        self.lbl_kameraG.setText(_translate("MainWindow", "Kamera"))
        self.lbl_kameraH.setText(_translate("MainWindow", "Kamera"))
        self.lbl_kameraD.setText(_translate("MainWindow", "Kamera"))
        self.label_3.setText(_translate("MainWindow", "Kamera3"))
        self.label_4.setText(_translate("MainWindow", "Kamera4"))
        self.label_5.setText(_translate("MainWindow", "Kamera5"))
        self.label_7.setText(_translate("MainWindow", "Kamera6"))
        self.label_8.setText(_translate("MainWindow", "Kamera7"))
        self.label_9.setText(_translate("MainWindow", "Kamera8"))
        self.lbl_kameraA.setText(_translate("MainWindow", "Kamera"))
        self.label_11.setText(_translate("MainWindow", "Kamera1"))
        self.label_27.setText(_translate("MainWindow", "Kamera2"))
        self.lbl_kameraA.hide()
        self.lbl_kameraB.hide()
        self.lbl_kameraC.hide()
        self.lbl_kameraD.hide()
        self.lbl_kameraE.hide()
        self.lbl_kameraF.hide()
        self.lbl_kameraG.hide()
        self.lbl_kameraH.hide()
        self.label.hide()
        self.label_2.hide()
        self.label.setText(_translate("MainWindow", "ziyaretci hedefe ulaştı"))
        self.label_2.setText(_translate("MainWindow", "ziyaretci hedefe ulaşamadı"))
        self.txt_rapor.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
